parser: "babel-eslint"
env:
  browser: true
  es6: true
extends: [
  'eslint:recommended',
  'plugin:flowtype/recommended',
  'plugin:react/recommended',
]
parserOptions:
  ecmaVersion: 6
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
plugins:
  - flowtype
  - react
settings:
  react:
    version: 15.3
    flowVersion: 0.57
globals:
  requirejs: false
  define: false
  jsRoutes: false
rules:
  no-mixed-spaces-and-tabs:
    - error
  linebreak-style:
    - error
    - unix
  semi:
    - error
    - always
  no-cond-assign:
    - warn
  no-console:
    - warn
  no-constant-condition:
    - warn
  no-control-regex:
    - warn
  no-debugger:
    - error
  no-dupe-args:
    - error
  no-dupe-keys:
    - error
  no-duplicate-case:
    - error
  no-empty:
    - warn
  no-empty-character-class:
    - warn
  no-extra-semi:
    - error
  no-func-assign:
    - warn
  no-invalid-regexp:
    - error
  no-irregular-whitespace:
    - warn
  no-obj-calls:
    - error
  no-sparse-arrays:
    - warn
  no-unexpected-multiline:
    - warn
  no-unreachable:
    - warn
  use-isnan:
    - error
  valid-typeof:
    - warn
  eqeqeq:
    - warn
    - smart
  no-alert:
    - warn
  no-caller:
    - error
  no-empty-function:
    - warn
  no-extra-bind:
    - warn
  no-fallthrough:
    - warn
  no-implicit-coercion:
    - warn
    - allow:
      - "!!"
  no-implicit-globals:
    - error
  no-native-reassign:
    - error
  no-octal:
    - warn
  no-param-reassign:
    - warn
  no-redeclare:
    - warn
  no-self-assign:
    - warn
  no-self-compare:
    - warn
  no-unused-expressions:
    - warn
  no-with:
    - error
  radix:
    - warn
  no-delete-var:
    - error
  no-shadow:
    - warn
  no-undef:
    - error
  no-unused-vars:
    - warn
  no-use-before-define:
    - error
    - functions: false
  no-useless-escape:
    - off
  react/prop-types:
    - warn
  react/display-name:
    - off
  react/no-string-refs:
    - warn
  react/no-find-dom-node:
    - off
  react/jsx-no-target-blank:
    - warn
  react/no-unescaped-entities:
    - warn

