#!/bin/bash

API_BASE_URL='http://9f3d400f.ngrok.io' \
AWS_ACCESS_KEY=AKIAIE7ZBTECOB5M444A \
AWS_SECRET_KEY='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' \
AWS_ROLE='arn:aws:iam::140476752418:role/LambdaExe-matteo' \
GITHUB_REPO_TOKEN='c7e95cf3fdf2184fed5a73bf8f0c9de54c384acd' \
SLACK_CLIENT_ID='20787119010.71176049680' \
SLACK_CLIENT_SECRET=653960aef44c5c8d7f5aa6eb7c6718c3 \
SLACK_REDIRECT_URL='http://9f3d400f.ngrok.io/authenticate/slack' \
activator "$@"
#-jvm-debug 9999 run
