#!/bin/bash

JAVA_OPTS='-Dconfig.file=conf/development.conf' \
API_BASE_URL='http://9f3d400f.ngrok.io' \
AWS_ACCESS_KEY='AKIAJGLCA7NGX3TYRTIA' \
AWS_SECRET_KEY='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' \
AWS_ROLE='arn:aws:iam::140476752418:role/LambdaExe-matteo' \
GITHUB_REPO_TOKEN='c7e95cf3fdf2184fed5a73bf8f0c9de54c384acd' \
SLACK_CLIENT_ID='20787119010.71176049680' \
SLACK_CLIENT_SECRET=653960aef44c5c8d7f5aa6eb7c6718c3 \
SLACK_REDIRECT_URL='http://9f3d400f.ngrok.io/authenticate/slack' \
activator "$@"
#-jvm-debug 9999 run
