// flow-typed signature: c4d87210382198d2e0beadec2a10e335
// flow-typed version: <<STUB>>/amdefine_v^1.0.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'amdefine'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'amdefine' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'amdefine/amdefine' {
  declare module.exports: any;
}

declare module 'amdefine/intercept' {
  declare module.exports: any;
}

// Filename aliases
declare module 'amdefine/amdefine.js' {
  declare module.exports: $Exports<'amdefine/amdefine'>;
}
declare module 'amdefine/intercept.js' {
  declare module.exports: $Exports<'amdefine/intercept'>;
}
