// flow-typed signature: de931ec5d05c396a580d9d4642c9a5a3
// flow-typed version: <<STUB>>/javascript-debounce_v1.0.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'javascript-debounce'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'javascript-debounce' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'javascript-debounce/dist/javascript-debounce' {
  declare module.exports: any;
}

declare module 'javascript-debounce/dist/javascript-debounce.min' {
  declare module.exports: any;
}

declare module 'javascript-debounce/scripts/build' {
  declare module.exports: any;
}

declare module 'javascript-debounce/scripts/stats' {
  declare module.exports: any;
}

declare module 'javascript-debounce/src/javascript-debounce' {
  declare module.exports: any;
}

// Filename aliases
declare module 'javascript-debounce/dist/javascript-debounce.js' {
  declare module.exports: $Exports<'javascript-debounce/dist/javascript-debounce'>;
}
declare module 'javascript-debounce/dist/javascript-debounce.min.js' {
  declare module.exports: $Exports<'javascript-debounce/dist/javascript-debounce.min'>;
}
declare module 'javascript-debounce/scripts/build.js' {
  declare module.exports: $Exports<'javascript-debounce/scripts/build'>;
}
declare module 'javascript-debounce/scripts/stats.js' {
  declare module.exports: $Exports<'javascript-debounce/scripts/stats'>;
}
declare module 'javascript-debounce/src/javascript-debounce.js' {
  declare module.exports: $Exports<'javascript-debounce/src/javascript-debounce'>;
}
