// flow-typed signature: 853225129a95a2a0b8a78d5232b1fb61
// flow-typed version: <<STUB>>/urijs_v1.18.1/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'urijs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'urijs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'urijs/src/IPv6' {
  declare module.exports: any;
}

declare module 'urijs/src/jquery.URI' {
  declare module.exports: any;
}

declare module 'urijs/src/jquery.URI.min' {
  declare module.exports: any;
}

declare module 'urijs/src/punycode' {
  declare module.exports: any;
}

declare module 'urijs/src/SecondLevelDomains' {
  declare module.exports: any;
}

declare module 'urijs/src/URI.fragmentQuery' {
  declare module.exports: any;
}

declare module 'urijs/src/URI.fragmentURI' {
  declare module.exports: any;
}

declare module 'urijs/src/URI' {
  declare module.exports: any;
}

declare module 'urijs/src/URI.min' {
  declare module.exports: any;
}

declare module 'urijs/src/URITemplate' {
  declare module.exports: any;
}

// Filename aliases
declare module 'urijs/src/IPv6.js' {
  declare module.exports: $Exports<'urijs/src/IPv6'>;
}
declare module 'urijs/src/jquery.URI.js' {
  declare module.exports: $Exports<'urijs/src/jquery.URI'>;
}
declare module 'urijs/src/jquery.URI.min.js' {
  declare module.exports: $Exports<'urijs/src/jquery.URI.min'>;
}
declare module 'urijs/src/punycode.js' {
  declare module.exports: $Exports<'urijs/src/punycode'>;
}
declare module 'urijs/src/SecondLevelDomains.js' {
  declare module.exports: $Exports<'urijs/src/SecondLevelDomains'>;
}
declare module 'urijs/src/URI.fragmentQuery.js' {
  declare module.exports: $Exports<'urijs/src/URI.fragmentQuery'>;
}
declare module 'urijs/src/URI.fragmentURI.js' {
  declare module.exports: $Exports<'urijs/src/URI.fragmentURI'>;
}
declare module 'urijs/src/URI.js' {
  declare module.exports: $Exports<'urijs/src/URI'>;
}
declare module 'urijs/src/URI.min.js' {
  declare module.exports: $Exports<'urijs/src/URI.min'>;
}
declare module 'urijs/src/URITemplate.js' {
  declare module.exports: $Exports<'urijs/src/URITemplate'>;
}
