version: 2
general:
  branches:
    only:
      - circle-build
jobs:
  build:
    working_directory: ~/circulate
    docker:
      - image: java:8
    steps:
      - checkout
      - run: echo "hello world"
