version: 2
jobs:
  build:
    branches:
      only:
        - circle-build
    docker:
      - image: ellipsis/circleci_primary:latest
        environment:
          DB_HOST: localhost
          DB_PORT: 5432
          # JAVA_TOOL_OPTIONS: '-Dfile.encoding=UTF8 -Duser.timezone=UTC'
          # _JAVA_OPTIONS: '-Xms512m -Xmx1024m -Xss2m'
      - image: postgres:9.6.2
        environment:
          POSTGRES_USER: ellipsis
          POSTGRES_DB: ellipsis-test
          POSTGRES_PASSWORD: ellipsis
    working_directory: ~//ellipsis
    steps:
      - checkout
      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgress && exit 1
      - run:
          name: Install npm dependencies
          command: |
            npm prune;npm install
      - run:
          name: Run JavaScript Linter
          command: |
            npm run lint
      - run:
          name: Run JavaScript Tests
          command: |
            pushd npm_modules/ellipsis-cal-date-format/; npm install; popd
            npm test
      - run:
          name: Run Activator Tests
          command: |
            activator test
