version: 2
general:
  branches:
    only:
      - circle-build
jobs:
  build:
    working_directory: ~/ellipsis
    docker:
      - image: java:8
      - image: postgres:9.6.2
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
