version: 2
jobs:
  build:
    # branches:
    #   only:
    #     - master
    docker:
      - image: ellipsis/circleci_primary:latest
        environment:
          DB_HOST: localhost
          DB_PORT: 5432
          # JAVA_TOOL_OPTIONS: '-Dfile.encoding=UTF8 -Duser.timezone=UTC'
          # _JAVA_OPTIONS: '-Xms512m -Xmx1024m -Xss2m'
      - image: postgres:9.6.2
        environment:
          POSTGRES_USER: ellipsis
          POSTGRES_DB: ellipsis-test
          POSTGRES_PASSWORD: ellipsis
    working_directory: /home/ellipsis
    steps:
      - checkout
      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgress && exit 1
      - run:
          name: Install npm dependencies
          command: |
            npm prune;npm install
      - run:
          name: Run JavaScript Linter
          command: |
            npm run lint
      - run:
          name: Run JavaScript Tests
          command: |
            pushd npm_modules/ellipsis-cal-date-format/; npm install; popd
            npm test
      - run:
          name: Run Activator Tests
          command: |
            activator test
      # create playapp image
      # store playapp image in Docker Hub
      # uploaded playapp image to s3 bucket
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            BOT_VERSION=`git rev-parse --short HEAD`
            echo application.version=\"${BOT_VERSION}\" > conf/version.conf
            activator docker:stage
      - run:
          name: Prepare the Elasticbeanstalk bundle
          command: |
            BOT_BUNDLE=$BOT_VERSION.zip
            BOT_BUNDLE_PATH=~/$BOT_BUNDLE
            mkdir -p target/docker/.ebextensions
            cp .ebextensions/* target/docker/.ebextensions/
            cp deploy/Docker* target/docker/
            pushd target/docker > /dev/null
            zip -qq -r $BOT_BUNDLE_PATH .
            popd > /dev/null
            popd > /dev/null


      - deploy:
          command: |
            - aws s3 cp $CIRCLE_ARTIFACTS/homebay-docker-$CIRCLE_SHA1.zip s3://homebay-deployments/homebay-docker-$CIRCLE_SHA1.zip
            # - aws elasticbeanstalk create-application-version --application-name HomeBay --version-label $CIRCLE_SHA1 --source-bundle S3Bucket=homebay-deployments,S3Key=homebay-docker-$CIRCLE_SHA1.zip --region us-east-1
            # - aws elasticbeanstalk update-environment --environment-name homebay-web --version-label $CIRCLE_SHA1 --region us-east-1
