#!/bin/sh

pushd `git rev-parse --show-toplevel`
touch conf/version.conf
echo application.version=\"`git rev-parse --short HEAD`\" >conf/version.conf
activator docker:stage
cp deploy/Docker* target/docker/
pushd target/docker
VERSION_LABEL=ellipsis-`git rev-parse --short HEAD`
BUNDLE=$VERSION_LABEL.zip
BUNDLE_PATH=~/Desktop/$BUNDLE
MAGENTA=`tput setaf 5`
GREEN=`tput setaf 2`
PLAIN=`tput sgr0`
zip -r $BUNDLE_PATH .
popd
popd

BUCKET=elasticbeanstalk-us-east-1-170937251085
APP_NAME="My First Elastic Beanstalk Application"

if ! type aws > /dev/null;
then

  echo -e "
You need to set up the aws CLI tools. Try ${GREEN}brew install awscli${PLAIN} if you’re using
brew, or go to ${GREEN}https://aws.amazon.com/cli/${PLAIN}.";

else

  if [ -z ${AWS_ELLIPSIS_PROFILE+x} ];
  then

    echo -e "
You need to set the ${GREEN}AWS_ELLIPSIS_PROFILE${PLAIN} env var with the
profile to use for AWS.

1. If you haven’t already, run ${GREEN}aws configure --profile ellipsis${PLAIN} to set up a
   profile.

   You will need an AWS access key and secret key. If you don’t have one, you
   can create a new one from the users page:

   ${GREEN}https://console.aws.amazon.com/iam/home?region=us-east-1#users${PLAIN}

   Use ${GREEN}text${PLAIN} for the output format, and ${GREEN}us-east-1${PLAIN} for the region.

2. Add a line to your ${GREEN}.bashrc${PLAIN} file:

   ${GREEN}export AWS_ELLIPSIS_PROFILE=ellipsis${PLAIN}

3. Open a new terminal or run ${GREEN}source ~/.bashrc${PLAIN}, then try again.";

  else

    S3_KEY=`date +'%Y-%m-%d'`-$BUNDLE
    echo -e "
${MAGENTA}Uploading ${GREEN}$BUNDLE${MAGENTA} to S3...${PLAIN}";
    aws --profile $AWS_ELLIPSIS_PROFILE s3 cp $BUNDLE_PATH s3://$BUCKET/$S3_KEY

    aws --profile $AWS_ELLIPSIS_PROFILE elasticbeanstalk create-application-version \
    --application-name "$APP_NAME" \
    --version-label $VERSION_LABEL \
    --source-bundle S3Bucket=$BUCKET,S3Key=$S3_KEY \
    --process;

  fi

fi
