#!/bin/sh

pushd `git rev-parse --show-toplevel`
touch conf/version.conf
echo application.version=\"`git rev-parse --short HEAD`\" >conf/version.conf
activator docker:stage
cp deploy/Docker* target/docker/
pushd target/docker
VERSION_LABEL=ellipsis-`git rev-parse --short HEAD`
BUNDLE=~/Desktop/$VERSION_LABEL.zip
zip -r $BUNDLE .
popd
popd

BUCKET=elasticbeanstalk-us-east-1-170937251085
APP_NAME="My First Elastic Beanstalk Application"

if ! type aws > /dev/null;

then echo "You need to set up the aws CLI tools";

else

  if [ -z ${AWS_ELLIPSIS_PROFILE+x} ];

  then echo "You need to set the AWS_ELLIPSIS_PROFILE env var with the profile to use for the AWS commands";

  else

    aws --profile $AWS_ELLIPSIS_PROFILE s3 cp $BUNDLE s3://bucket/$BUCKET/

    aws --profile $AWS_ELLIPSIS_PROFILE elasticbeanstalk create-application-version \
    --application-name $APP_NAME \
    --version-label $VERSION_LABEL \
    --source-bundle S3Bucket="$BUCKET",S3Key="$BUNDLE";

  fi

fi
