env:
  browser: false
  node: true
parserOptions:
  ecmaFeatures:
    jsx: false
globals:
  event: false
  context: false
  callback: true
  $CONTEXT_PARAM: false
plugins: []
rules:
  no-unused-vars:
    - off
  no-console:
    - off
