FROM elasticsearch:2.3

# RUN /usr/share/elasticsearch/bin/plugin install --batch cloud-aws
RUN /usr/share/elasticsearch/bin/plugin install --batch mobz/elasticsearch-head
RUN /usr/share/elasticsearch/bin/plugin install --batch appbaseio/mirage
